apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    demo: helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      demo: helm
  template:
    metadata:
      labels:
        app: nginx
        demo: helm
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    demo: deployment
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port